# Generated by Django 6.0.3 on 2026-03-12 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activities', models.TextField()),
                ('Week_Number', models.IntegerField()),
                ('Supervisor', models.CharField()),
                ('Supervisor_Comment', models.TextField()),
                ('Progress', models.IntegerField()),
                ('Hours_Worked', models.IntegerField()),
                ('Remaining_time_for_Internship', models.IntegerField()),
                ('Student_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
