# Generated by Django 5.2.12 on 2026-03-12 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_weeklylogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weeklylogs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='internshipPlacements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=100)),
                ('Company_location', models.CharField(max_length=100)),
                ('Supervisor', models.CharField(max_length=100)),
                ('Supervisor_email', models.EmailField(max_length=254)),
                ('Supervisor_phone', models.CharField(max_length=20)),
                ('Internship_start_date', models.DateField()),
                ('Internship_end_date', models.DateField()),
                ('Student_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
