# Generated by Django 6.0.3 on 2026-03-27 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_student_id_customuser_stuff_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='academicSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stuff_id', models.CharField(max_length=20, unique=True)),
                ('Phone_number', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('Phone_number', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('Place_Of_Work', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='internSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stuff_id', models.CharField(max_length=20, unique=True)),
                ('Phone_number', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_supervisor_profile', to=settings.AUTH_USER_MODEL)),
                ('Supervises_Who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_students', to='users.student')),
            ],
        ),
    ]
