# Generated by Django 6.0.3 on 2026-04-16 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_academicsupervisor_student_internsupervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week_Number', models.PositiveIntegerField()),
                ('Submittion_Date', models.DateField(auto_now_add=True)),
                ('Activities_Done', models.TextField()),
                ('Challenges', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('Student_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to=settings.AUTH_USER_MODEL)),
                ('Supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
