# Generated by Django 6.0.3 on 2026-05-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_academicsupervisor_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentlogNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('studentlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.studentlog')),
            ],
        ),
    ]
