# Generated by Django 6.0.3 on 2026-05-05 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_studentlognotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='weeklylogNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
