# Generated by Django 6.0.3 on 2026-05-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_messagenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagenotification',
            name='Academic_Supervisor',
        ),
        migrations.RemoveField(
            model_name='messagenotification',
            name='Intern_Supervisor',
        ),
        migrations.RemoveField(
            model_name='messagenotification',
            name='Student',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageNotification',
        ),
    ]
