# Generated by Django 6.0.3 on 2026-05-07 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_messagenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
