# Generated by Django 6.0.3 on 2026-05-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_studentlog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlog',
            name='created_at',
        ),
    ]
