# Generated by Django 6.0.3 on 2026-05-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_weeklylogs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylogs',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
