# Generated by Django 6.0.3 on 2026-06-08 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_weeklylogs_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipplacements',
            name='Student_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagenotification',
            name='recepient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepient_of_message_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_of_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_of_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='Student_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='Supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentlognotification',
            name='recepient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentlognotification',
            name='studentlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='users.studentlog'),
        ),
        migrations.AlterField(
            model_name='supervisorlog',
            name='Student_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisorlog',
            name='Supervisor_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisormessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisormessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisormessage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklylognotification',
            name='recepient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklylogs',
            name='Student_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
